swagger: '2.0'
info:
  description: An API to find national holidays by country
  version: 1.0.0
  title: Holsfinder
  contact:
    email: bkaoluborode@gmail.com

tags:
- name: countries
  description: All listed countries
- name: holidays
  description: All holidays associated with a country

paths:
  /api/v1/countries:
    get:
      tags:
        - countries
        summary: gets all supported countries on api
        description: ''
        produces:
        - application/json
        responses:
          200:
            description: successful response
            schema:
              type: object
              $ref: '#/definitions/Countries'
          400:
            description: bad input parameter
  
  /api/v1/holidays/{country}/{month}:
    get:
      tags:
        - holidays
        summary: gets holidays by country
        description: ''
        produces:
          - application/json
        parameters:
          - name: country
            in: path
            description: country to get holidays from
            required: true
            type: string
          - name: month
            in: path
            description: holidays for the particular month
            required: true
            type: integer
            format: int32
        responses:
          200:
            description: successful response
            schema:
              type: object
              $ref: '#/definitions/Holidays'
          400:
            description: bad input parameter

schemes:
  - https
        
